### ISSUE TITLE
Qualidade (aula-11)

### ISSUE THREAD

**Issue by kyriosdata** [mbdjair/cs-2019-01#14]
O código, seja JavaScript ou Java, precisa de documentação, nomes adequados, estilo de codificação, testes, análise estática e outros. Vamos esclarecer todos estes itens na aula de amanhã?

**Comment by mbdjair** [comment]
Até amanhã eu já realizo algumas mudanças na aula 11 para uma reavaliação

**Comment by kyriosdata** [comment]
Não esqueça de esclarecer suas dúvidas.

Fábio
